name: Release WP Plugin

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create plugin ZIP
        run: |
          mkdir -p dist/wt-wp-agent
          cp -r plugin/* dist/wt-wp-agent/
          cd dist
          zip -r wt-wp-agent.zip wt-wp-agent