name: Release WP Plugin

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create plugin ZIP
        run: |
          mkdir -p dist
          cd plugin
          zip -r ../dist/wt-wp-agent.zip .